excluded:
  - .swiftpm
  - Tests

disabled_rules:
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closure_body_length
  - conditional_returns_on_newline
  - convenience_type
  - cyclomatic_complexity
  - discouraged_object_literal
  - duplicate_enum_cases
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_length
  - file_name
  - file_types_order
  - for_where
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - ibinspectable_in_extension
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - large_tuple
  - let_var_whitespace
  - nesting
  - nimble_operator
  - no_fallthrough_only
  - no_grouping_extension
  - notification_center_detachment
  - nslocalizedstring_require_bundle
  - number_separator
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_string_enum_value
  - required_deinit
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - test_case_accessibility
  - trailing_closure
  - type_body_length
  - type_contents_order
  - type_name
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - vertical_whitespace_between_cases
  - xct_specific_matcher
  - xctfail_message

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - inclusive_language
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_space_in_method_call
  - nslocalizedstring_key
  - nsobject_prefer_isequal
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - orphaned_doc_comment
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - statement_position
  - static_operator
  - strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

identifier_name:
  min_length: 2
  excluded:
    - id
    - _schemaName

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
