name: build

on:
  push:
    branches:
        - main
        - develop
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches:
        - main
        - develop
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
  workflow_dispatch:
    branches:
        - main
        - develop
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
