name: build

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
